{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pump State",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (state) (pump_101_state_status == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sensor-001",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "sensor_001{}", "legendFormat": "{{element_id}}" }
   ]
  },
  {
   "title": "pump_101",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "pump_101_measurements_bearing_temperature_value",
     "legendFormat": "{{element_id}}"
    },
    {
     "expr": "pump_101_measurements_bearing_temperature_health",
     "legendFormat": "{{element_id}}"
    }
   ]
  }
 ]
}